apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-listener
  template:
    metadata:
      labels:
        app: email-listener
    spec:
      serviceAccountName: email-listener-sa
      containers:
      - name: email-listener
        image: asia-south1-docker.pkg.dev/final-pdf-loa/dit-repo/email-listener:v14
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: app-config-v4