apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-processor
  template:
    metadata:
      labels:
        app: pdf-processor
    spec:
      serviceAccountName: pdf-processor-sa
      containers:
      - name: pdf-processor
        image: asia-south1-docker.pkg.dev/final-pdf-loa/dit-repo/pdf-processor:v9
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: app-config-v4
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "final-pdf-loa:asia-south1:dit-db"